---
swagger: "2.0"
info:
  description: "Contains all available API endpoints in this codebase"
  version: "1.0.6"
  title: "Argent Bank API documentation"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v2"
tags:
- name: "transactions"
  description: "Operations related to transactions"
schemes:
- "http"
paths:
  /transactions/{accountId}:
    get:
      tags:
      - "transactions"
      summary: "Retrieves a list of all transactions for the last month"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Bearer (apiKey)"
        required: true
        type: "string"
      responses:
        200:
          description: "List of transactions retrieved successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
        500:
          description: "Internal Server Error"
  /transactions/{transactionId}:
    get:
      tags:
      - "transactions"
      summary: "Fetches details for a specific transaction"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Bearer (apiKey)"
        required: true
        type: "string"
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: "Transaction not found"
        500:
          description: "Internal Server Error"
    patch:
      tags:
      - "transactions"
      summary: "Partially updates the details of the specified transaction"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      - in: "body"
        name: "body"
        description: "Updated details"
        required: true
        schema:
          $ref: "#/definitions/Transaction"
      - name: categoryId
        in: query
        description: "ID of the category (optional)"
        required: false
        type: number
      - name: note
        in: query
        description: "Note (optional)"
        required: false
        type: string
      responses:
        200:
          description: "Details of the transaction updated successfully"
        400:
          description: "Invalid value"
        404:
          description: "Transaction not found"
        500:
          description: "Internal Server Error"
      security:
      - Bearer: []
    delete:
      tags:
      - "transactions"
      summary: "Removes the details of the specified transaction"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      - in: "body"
        name: "body"
        description: "All details"
        required: true
        schema:
          $ref: "#/definitions/Transaction"
      responses:
        200:
          description: "Details of the transaction deleted successfully"
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: "Transaction not found"
        500:
          description: "Internal Server Error"
      security:
      - Bearer: []
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  ApiResponse:
    type: "object"
    properties:
      id:
        type: "number"
      title:
        type: "string"
      amount:
        type: "number"
      description:
        type: "string"
  Transaction:
    type: "object"
    required:
    - "id"
    - "account"
    - "date"
    - "amount"
    properties:
      id:
        type: "number"
      account:
        type: "string"
      date:
        type: "string"
        format: "DD/MM/YY"
      description:
        type: "string"
      transactionType:
        type: "string"
      category:
        type: "string"
      note: 
        type: "string"
      amount:
        type: "number"
      balance:
        type: "number"

